name: Push image
on:
  workflow_call:
    inputs:
      role:
        description: The AWS role to assume
        type: string
        required: true
      region:
        description: The AWS region to use
        type: string
        required: true
      name:
        description: The name of the image
        type: string
        required: true
      dockerfile:
        description: The path to the relevant Dockerfile
        type: string
        required: false
        default: Dockerfile
      build-path:
        description: The build path to use
        type: string
        required: false
        default: .

jobs:
  push-image:
    name: Push image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Authenticate to Amazon Web Services
        uses: aws-actions/configure-aws-credentials@v5
        id: aws
        with:
          role-to-assume: ${{ inputs.role }}
          aws-region: ${{ inputs.region }}

      - name: Build and push image
        env:
          name: ${{ inputs.name }}:latest
          registry: >-
            ${{ steps.aws.outputs.aws-account-id }}.dkr.ecr.${{ inputs.region }}.amazonaws.com
        run: |-
          aws ecr-public get-login-password --region us-east-1 | \
              docker login --username AWS --password-stdin public.ecr.aws
          aws ecr get-login-password --region "${{ inputs.region }}" | \
              docker login --username AWS --password-stdin "${registry}"
          docker build --tag "${registry}/${name}" --file "${{ inputs.dockerfile }}" \
              "${{ inputs.build-path }}"
          docker push "${registry}/${name}"
