name: Update floating tag
on:
  release:
    types: [released]

jobs:
  update-floating-tag:
    name: Update floating tag
    uses: ./.github/workflows/github/update-floating-tag.yml
    permissions:
      contents: write
